%YAML:1.0

# Camera calibration and distortion parameters (OpenCV)
Camera.fx: 707.0912
Camera.fy: 707.0912
Camera.cx: 601.8873
Camera.cy: 183.1104

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0

Camera.width: 1241
Camera.height: 376

# stereo baseline times fx
Camera.bf: 379.8145

# ORB Extractor Threshold
# 初始门限
ORBExtractor.initTHFAST: 20
# 较差时使用的门限
ORBExtractor.minTHFAST: 5
# 特征点数量
ORBExtractor.nFeatures: 200

# ORBMatcher 的阈值
ORBMatch.TH_LOW : 50
ORBMatch.TH_HIGH : 100
ORBMatch.HISTO_LENGTH : 30

# Viewer Setting
# 可视化中相机的大小
View.cameraSize : 0.1
View.width : 1280
View.height : 720
View.UI_WIDTH: 240



